Feature/dona/aca 26 aca 39
mattheri/academoney pull request #11
Opened 2024-05-01 00:19 UTC by Dona-D32

Corrections et ajustements effectués :
* Suppression des commentaires inutiles.
* Modification des propriétés en facultatif et ajout de valeurs par défaut lorsque cela est approprié.
* Ajout du prop label.
 *Remplacement des éléments <a> par le composant Link de Next.js pour une meilleure expérience utilisateur.
 *Suppression des classes inutiles.
Le code a été optimisé dans la mesure du possible. 
Je continue à travailler pour améliorer encore la qualité du code.

2024-05-01 02:14 UTC, carocadieux approved these changes
C'est bien ton composant input pour tes styles! Parcontre je suis pas très habile avec tailwin, je me demandais pourquoi il y a autant de div? Je m'y perd un peu. J'essayerai d'analyser ça! Sinon je crois comprendre ce que tu as fait et ça me semble bien. Good job!

2024-05-02 19:09 UTC, JoMesss123 reviewed
j'ai rien a dire

2024-05-02 19:11 UTC, JoMesss123 approved these changes

2024-05-15 02:03 UTC, mattheri requested changes

2024-05-15 02:03 UTC, mattheri commented on app/components/input.tsx
> +"use client"; // Utilisation du client-side rendering pour ce composant
Pour quelle raison?

2024-05-15 02:03 UTC, mattheri commented on app/components/loginForm.tsx
> +"use client"; // Utilisation du client-side rendering pour ce composant
Pour quelle raison?

2024-05-22 03:06 UTC, merged