Ajouté la fonction d'ajouter des événements au calendrier
mattheri/academoney pull request #17
Opened 2024-05-07 20:13 UTC by thiviergejonathan

- J'ai créé la fonction permettant d'ajouter des événements au calendrier.
- - Cliquez sur une journée dans le calendrier, inscrivez le nom de l'événement puis cliquez sur 'Ajouter' pour ajouter.
- - Le nouvel événement est ajouté et apparaît dans le calendrier ainsi que dans la liste des événements au bas.
- J'ai également ajusté le style pour qu'il reflète le thème proposé dans le document de design.

2024-05-07 20:15 UTC, thiviergejonathan commented on app/modal/modal.tsx
Oops! Je me rend compte que j'ai quelques fichiers TEST que je n'aurais pas dû 'pusher'. À effacer!

2024-05-07 20:15 UTC, thiviergejonathan commented on app/testcalendrier/page.tsx
Un autre fichier à effacer! Désoler! :)

2024-05-07 20:17 UTC, thiviergejonathan commented on http/client.ts
Je ne comprend pas pourquoi ce fichier (ainsi que http.ts, index.ts, ...) sont aussi inclus dans mon PR?

2024-05-15 01:56 UTC, mattheri requested changes

2024-05-15 01:56 UTC, mattheri commented on app/calendrier/page.tsx
> +"use client";
Voir ma branche ACA-66 svp.

2024-05-15 01:56 UTC, mattheri commented on app/modal/modal.tsx
git rm app/modal/modal.tsx --cached

2024-05-15 01:56 UTC, mattheri commented on app/testcalendrier/page.tsx
git rm app/testcalendrier/page.tsx --cached

2024-05-15 01:56 UTC, mattheri commented on app/calendrier/page.tsx
> +        <ul>
Pourrait être dans son propre component. Un événement est une Transaction qui vient de l'API, on peut donc ajouter pas mal plus d'informations aussi.

2024-05-15 01:56 UTC, mattheri commented on app/calendrier/page.tsx
> +interface Event {
Voir ma branche ACA-66 svp. Ça ne reflète pas du tout ce qui vient de l'API.

2024-05-19 23:38 UTC, merged