Feature/caro/aca 47
mattheri/academoney pull request #19
Opened 2024-05-10 14:46 UTC by carocadieux

-ajout du dropdown revenu, dépense
-création d'un composant bouton réutilisable

2024-05-14 16:29 UTC, Dona-D32 approved these changes

2024-05-14 22:52 UTC, anthonylemay approved these changes
Tout me semble bon!

2024-05-15 01:52 UTC, mattheri requested changes
Très bon travail! Quelques petits changements (use client dans la page) mais sinon, très bien!

2024-05-15 01:52 UTC, mattheri commented on common/components/Button/Button.style.ts
> +import { cva } from "cva";
Good job pour avoir utilisé cva mais je ne comprends pas à quoi il sert? Il n'y a que 3 classes, pourquoi ne pas les mettre simplement dans l'attribut className?

2024-05-15 01:52 UTC, mattheri commented on common/components/Button/Button.tsx
> +export const Button: FC<Props> = forwardRef<HTMLButtonElement, Props>( ({ children, className, type="button" }, ref)=> {
GJ! 🔥

2024-05-16 00:46 UTC, carocadieux commented on common/components/Button/Button.style.ts
> +import { cva } from "cva";
je pensais peut-être mettre des variants éventuellement

2024-05-19 23:33 UTC, mattheri approved these changes
Simplement faire le petit changement que j'ai demandé, sinon GJ 🔥

2024-05-19 23:33 UTC, mattheri commented on common/components/Button/Button.tsx
> +  className?: string;
Pas besoin, ce props est déjà compris dans les props de base que tu as mis: ButtonHTMLAttributes<HTMLButtonElement>

2024-05-22 01:27 UTC, merged