Feature dona / aca 34 / aca 71
mattheri/academoney pull request #20
Opened 2024-05-14 18:59 UTC by Dona-D32

- Modification dans l'affichage du modal pour l'inscription.
- Modification dans le composant LOGO pour accepter des props width et height pour contrôler sa taille lors de sa réutilisation.
- Création du composant footer et de la page testFooter pour tester l'affichage.

2024-05-15 01:50 UTC, mattheri requested changes

2024-05-15 01:50 UTC, mattheri commented on app/components/footer.tsx
> +const Footer: FC = () => {
Le component irait dans le dossier common et non app/components. App ne devrait contenir que les routes, pages, loading, errors, etc...

2024-05-15 01:50 UTC, mattheri commented on app/components/inscriptionForm.tsx
> +const InscriptionForm = () => {
Ça va dans auth/components. Met le nom du component en PascalCase svp

2024-05-15 01:50 UTC, mattheri commented on app/components/inscriptionForm.tsx
> +        <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="firstName" type="text" value={firstName} onCh
Pourrait être bien si tu pouvais réutiliser quelques Inputs qui ont déjà été faits.

2024-05-15 01:50 UTC, mattheri commented on app/components/inscriptionForm.tsx
> +  const [firstName, setFirstName] = useState('');
Pas de controlled inputs svp

2024-05-15 01:50 UTC, mattheri commented on app/components/inscriptionModal.tsx
> +interface InscriptionModalProps {
Utiliser type pas interface svp

2024-05-15 01:50 UTC, mattheri commented on app/components/loginForm.tsx
> +// components/LoginForm.tsx
Ça va dans auth/components

2024-05-15 01:50 UTC, mattheri commented on app/components/logo.tsx
> +// components/Logo.tsx
Ça va dans common/components

2024-05-15 01:50 UTC, mattheri commented on app/components/pageContainer.tsx
> +import { ReactNode } from 'react';
Idem

2024-05-15 01:50 UTC, mattheri commented on app/components/textInput.tsx
> +"use client";
Pourquoi use client? Pourquoi il n'a pas été réutilisé dans le formulaire d'inscription?

2024-05-15 01:50 UTC, mattheri commented on app/testFooter/page.tsx
> +import { FC } from 'react';
À supprimer si non utilisé

2024-05-15 14:50 UTC, Dona-D32 commented on app/components/footer.tsx
> +const Footer: FC = () => {
Salut Mathieu, oui j'avais pas déplacé mon code, car je voulais garder un certain contrôle sur ce que j'avais fait jusqu'à présent et être certains que tout est bon avant de disposer dans le bon dossier.

2024-05-15 15:25 UTC, Dona-D32 commented on app/components/inscriptionForm.tsx
> +const InscriptionForm = () => {
J'ai  mis mon code à jour avec le git, mais je ne vois pas le dossier auth, je l'ai donc ajouté.

2024-05-15 15:38 UTC, Dona-D32 commented on app/components/textInput.tsx
> +"use client";
J'ai retiré, je l'avais mis sur tout mes composants au début avant de bien comprendre son fonctionnement, j'ai oublié de l'enlever.

2024-05-15 15:40 UTC, Dona-D32 commented on app/testFooter/page.tsx
> +import { FC } from 'react';
je l'utilise pour tester l'affichage de mon footer, je sais pas comment envoyer du code sur github sans  envoyer toutes les modifications de code et pouvoir ainsi garder ce fichier test pour moi.

2024-05-15 15:55 UTC, Dona-D32 commented on app/components/inscriptionModal.tsx
> +interface InscriptionModalProps {
Je ne suis pas encore totalement familiarisée avec TypeScript, mais je compte approfondir mes connaissances sur les différences entre type et interface. D’après ce que j’ai pu observer, type semble permettre une plus grande complexité. J’espère être en mesure de l’utiliser de manière efficace à l’avenir.

2024-05-15 16:39 UTC, Dona-D32 commented on app/components/inscriptionForm.tsx
> +        <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="firstName" type="text" value={firstName} onCh
J'ai utilisé le FormInput de Caroline.

2024-05-16 00:27 UTC, mattheri requested changes

2024-05-16 00:27 UTC, mattheri commented on app/auth/components/InscriptionForm.tsx
> +import { FormEvent } from 'react';
Sors le sous-dossier `auth` du dossier `app` et met le à la racine svp.

2024-05-16 01:28 UTC, Dona-D32 commented on app/auth/components/InscriptionForm.tsx
> +import { FormEvent } from 'react';
En déplaçant le dossier auth, je perds tout mon css, le même soucis que j'ai recontré cette après-midi avec le footer et la navbar et j'avais réglé le problème à 80% en créant un dossier layout dans le commun/components, mais la je trouve pas de solution et avec la fatigue de la journée peu probable que j'y arrive ce soir.

2024-05-16 01:51 UTC, mattheri commented on app/auth/components/InscriptionForm.tsx
> +import { FormEvent } from 'react';
Dans la branche develop il y a déjà un sous dossier auth. Les styles Tailwind fonctionnent. Tu peux voir comment j’ai fait pour les faires fonctionner dans le fichier tailwind.config.ts

2024-05-16 01:59 UTC, Dona-D32 commented on app/auth/components/InscriptionForm.tsx
> +import { FormEvent } from 'react';
Je penses que j'ai trouvé, mon dossier tailwind.config.ts n'a pas mes ajouts dans le content: const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./calculator/**/*.{js,ts,jsx,tsx,mdx}",
    
  ],

2024-05-16 02:08 UTC, Dona-D32 commented on app/auth/components/InscriptionForm.tsx
> +import { FormEvent } from 'react';
Tout fonctionne, c'est fou de passer autant de temps à chercher une erreur et voir que c'était juste ça. :-(

2024-05-16 12:29 UTC, mattheri commented on app/auth/components/InscriptionForm.tsx
> +import { FormEvent } from 'react';
Si tu fais `git checkout develop` puis `git pull origin develop` puis `git checkout Feature-dona-/-ACA-34-/-ACA-71` et finalement `git merge develop` tu aurais eu ces changements déjà dans ton fichier tailwind.config.ts.

2024-05-19 23:31 UTC, mattheri approved these changes
GJ 🔥

2024-05-21 23:42 UTC, meganmartel approved these changes

2024-05-22 00:19 UTC, JoMesss123 commented
c est bon

2024-05-22 00:20 UTC, JoMesss123 approved these changes

2024-05-22 03:06 UTC, merged