Commit de CalendarSlider
mattheri/academoney pull request #24
Opened 2024-05-22 01:00 UTC by nacermouterfi

2024-05-28 17:12 UTC, nacermouterfi commented
Le premier commit je l'ai tout à fait supprimé pour le remplacer par ce dernier. Après avoir discuté avec Jonathan qui a travaillé sur le calendrier, mais le slider-calendrier  je n'ai pas trouvé son role d'ou ma difficulté à trancher. Toutefois, cette partie de slider est ajuster autrement à faire ressortir tous ses utilités dans la page.

2024-05-30 14:32 UTC, thiviergejonathan requested changes
Bon travail. Je pense que la partie principale de ton calendrier pourrait être divisé en plusieurs Components.

2024-05-30 14:32 UTC, thiviergejonathan commented on slide-calendar/components/slidecalendar/SlideCalendarBox.tsx
> +  const [selectedMonth, setSelectedMonth] = useState<Month | null>(null);
Ça ne serait pas mieux d'utiliser les Contexts ici au lieu des States?

2024-05-30 14:32 UTC, thiviergejonathan commented on slide-calendar/components/slidecalendar/SlideCalendarBox.tsx
> +    </div>
Idéalement, il faudrait réutiliser le calendrier que moi et l'autre Jonathan avons créé. Si ce n'est pas possible, je pense qu'il faudrait séparer ça en plusieurs Components.

2024-05-30 14:32 UTC, thiviergejonathan commented on slide-calendar/server/slidecalendarUtils.ts
> +
Est-ce que le code de ce fichier pourrait aller dans calendar/services/CalendarServices.ts?

2024-06-05 17:34 UTC, merged