Feature/dona/aca 26
mattheri/academoney pull request #8
Opened 2024-04-29 18:13 UTC by Dona-D32

2024-04-29 19:23 UTC, mattheri requested changes
Overall, good job! Je trouves qu'il manque un peu de "componentization" et de segmentation. Aussi, quelques pratiques qui gagneraient à être améliorées par-ci par là mais absolument rien d'alarmant!

2024-04-29 19:23 UTC, mattheri commented on app/login/page.tsx
> +"use client";
Une page ne devrait pas être mise en `"use client"`. Ça fait en sorte que l'on crée la page entière en utilisant le rendering client. On veut pouvoir utiliser le plus possible le server side rendering vu que c'est meilleur pour le SEO et les performances. Ce que tu peux faire c'est extraire ton code dans un component à part et mettre la directive `"use client"` dans ce component. Tu importes ensuite ce component dans la page.

2024-04-29 19:23 UTC, mattheri commented on app/login/page.tsx
>    const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
Nous allons utiliser les [Server actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations) de Next.js. Je suis en train de les définir. Je te conseille donc de lire sur les server actions et d'expérimenter avec!

2024-04-29 19:23 UTC, mattheri commented on app/login/page.tsx
> +            <div>
Devrait-on extraire le input avec son label dans son propre component afin que nous puissions réutiliser les styles partoutu?

2024-04-29 19:23 UTC, mattheri commented on app/login1/page.tsx
> +import React, { useState, FormEvent } from 'react';
Pas besoin d'importer React au complet, simplement `import { useState } from 'react'`. Aussi, on ne veut pas bundler les types dans le bundle final. Donc ajoutes `import type { FormEvent } from 'react'`.

2024-04-29 19:23 UTC, mattheri commented on app/login1/page.tsx
> +"use client";
Une page ne devrait pas être mise en "use client". Ça fait en sorte que l'on crée la page entière en utilisant le rendering client. On veut pouvoir utiliser le plus possible le server side rendering vu que c'est meilleur pour le SEO et les performances. Ce que tu peux faire c'est extraire ton code dans un component à part et mettre la directive "use client" dans ce component. Tu importes ensuite ce component dans la page.

2024-04-29 19:23 UTC, mattheri commented on app/login1/page.tsx
> +  const [email, setEmail] = useState('');
Vu qu'on utilise le server side rendering, est-ce qu'on ne veut pas utiliser des uncontrolled inputs au final?

2024-04-29 19:23 UTC, mattheri commented on app/login1/page.tsx
> +  const handleSubmit = (e: FormEvent<HTMLFormElement>) => {
Nous allons utiliser les [Server actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations) de Next.js. Je suis en train de les définir. Je te conseille donc de lire sur les server actions et d'expérimenter avec!

2024-04-29 19:23 UTC, mattheri commented on app/login1/page.tsx
> +                      <label htmlFor="email-address" className="sr-only">Courriel</label>
Pourquoi le lable est en `sr-only`?

2024-04-29 19:23 UTC, mattheri commented on app/login1/page.tsx
> +                        onChange={(e) => setEmail(e.target.value)}
Extraire les fonctions dans le component direct. Sinon, à chaque re-render, on recrée une autre fonction. Au final, le'empreinte mémoire en sera plus grande.

Donc:

```typescript
const onEmailUpdate = (event: ChangeEvent) => setEmail(event.target.value)

...

<input onChange={onEmailUpdate} />
```

2024-04-29 19:23 UTC, mattheri commented on app/login1/page.tsx
> +                        onChange={(e) => setEmail(e.target.value)}
Pour tous les inputs

2024-04-29 20:24 UTC, Dona-D32 commented on app/login1/page.tsx
> +                      <label htmlFor="email-address" className="sr-only">Courriel</label>
J'avais lu que c'était une pratique courante, je vais le changer pour le mettre visible pour tous les utilisateurs.

2024-04-29 23:56 UTC, mattheri commented on app/login1/page.tsx
> +                      <label htmlFor="email-address" className="sr-only">Courriel</label>
Le sr-only c'est utilisé pour l'accessibilité. Ça veut dire Screen Reader Only. Ça cache le label, mais on veut le montrer. Le screen reader va voir le label même si on le montre.

2024-04-30 00:00 UTC, mattheri commented
J'ai aussi remarqué que tu ne target pas la bonne branche, il faut que tu target `develop` au lieu de `main`

2024-04-30 00:19 UTC, Wjat777 commented
Le code commité donne l'erreur suivante (le npm install a était fait en mode force) : 
Est-ce que manque de fichiers dans votre commit?


`react-dom.development.js:38560 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
app-index.tsx:25 Warning: Did not expect server HTML to contain a <div> in <div>.
    at div
    at form
    at div
    at div
    at LoginPage (webpack-internal:///(app-pages-browser)/./app/login/page.tsx:11:78)
    at ClientPageRoot (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/client-page.js:14:11)
    at InnerLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:242:11)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:346:11)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:160:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:227:11)
    at RenderFromTemplateContext (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at OuterLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:367:11)
    at InnerLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:242:11)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at LoadingBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:346:11)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:160:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:227:11)
    at RenderFromTemplateContext (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/render-from-template-context.js:16:44)
    at OuterLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:367:11)
    at body
    at html
    at RootLayout (Server)
    at RootLayout (Server)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:74:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:82:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:76:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:84:11)
    at DevRootNotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/dev-root-not-found-boundary.js:33:11)
    at ReactDevOverlay (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/app/ReactDevOverlay.js:87:9)
    at HotReload (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/app/hot-reloader-client.js:321:11)
    at Router (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:207:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:113:9)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:160:11)
    at AppRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:577:13)
    at ServerRoot (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:112:27)
    at Root (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:117:11)
window.console.error @ app-index.tsx:25
console.error @ hydration-error-info.ts:72
printWarning @ react-dom.development.js:94
error @ react-dom.development.js:68
warnForDeletedHydratableElement @ react-dom.development.js:35133
didNotHydrateInstance @ react-dom.development.js:36252
warnUnhydratedInstance @ react-dom.development.js:6795
warnIfUnhydratedTailNodes @ react-dom.development.js:7414
popHydrationState @ react-dom.development.js:7383
completeWork @ react-dom.development.js:19764
completeUnitOfWork @ react-dom.development.js:25963
performUnitOfWork @ react-dom.development.js:25759
workLoopConcurrent @ react-dom.development.js:25734
renderRootConcurrent @ react-dom.development.js:25690
performConcurrentWorkOnRoot @ react-dom.development.js:24504
workLoop @ scheduler.development.js:256
flushWork @ scheduler.development.js:225
performWorkUntilDeadline @ scheduler.development.js:534
app-index.tsx:25 Warning: An error occurred during hydration. The server HTML was replaced with client content in <#document>.
window.console.error @ app-index.tsx:25
console.error @ hydration-error-info.ts:72
printWarning @ react-dom.development.js:94
error @ react-dom.development.js:68
errorHydratingContainer @ react-dom.development.js:36301
recoverFromConcurrentError @ react-dom.development.js:24593
performConcurrentWorkOnRoot @ react-dom.development.js:24542
workLoop @ scheduler.development.js:256
flushWork @ scheduler.development.js:225
performWorkUntilDeadline @ scheduler.development.js:534
6on-recoverable-error.ts:18 Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:6981:1)
    at popHydrationState (react-dom.development.js:7384:1)
    at completeWork (react-dom.development.js:19764:1)
    at completeUnitOfWork (react-dom.development.js:25963:1)
    at performUnitOfWork (react-dom.development.js:25759:1)
    at workLoopConcurrent (react-dom.development.js:25734:1)
    at renderRootConcurrent (react-dom.development.js:25690:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:24504:1)
    at workLoop (scheduler.development.js:256:1)
    at flushWork (scheduler.development.js:225:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:534:1)
throwOnHydrationMismatch @ react-dom.development.js:6981
popHydrationState @ react-dom.development.js:7384
completeWork @ react-dom.development.js:19764
completeUnitOfWork @ react-dom.development.js:25963
performUnitOfWork @ react-dom.development.js:25759
workLoopConcurrent @ react-dom.development.js:25734
renderRootConcurrent @ react-dom.development.js: [...]

2024-04-30 01:38 UTC, thiviergejonathan approved these changes

2024-04-30 02:12 UTC, closed without merging

2024-04-30 02:12 UTC, mattheri commented
Une autre PR qui adresse les changements a été ouverte